# Generated by Django 5.0.1 on 2026-01-16 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agencia",
            fields=[
                ("id_agencia", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(max_length=200)),
                ("responsable", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Agencia",
                "verbose_name_plural": "Agencias",
                "db_table": "agencias",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionOperativa",
            fields=[
                (
                    "id_configuracion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "capital_total_activos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "meta_volumen_diario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("perfiles_listos_operar", models.IntegerField(default=0)),
                ("perfiles_en_descanso", models.IntegerField(default=0)),
                (
                    "umbral_saldo_critico",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("actualizar_meta_diariamente", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuración Operativa",
                "verbose_name_plural": "Configuraciones Operativas",
                "db_table": "configuracion_operativa",
            },
        ),
        migrations.CreateModel(
            name="Distribuidora",
            fields=[
                (
                    "id_distribuidora",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("deportes", models.JSONField(default=list)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Distribuidora",
                "verbose_name_plural": "Distribuidoras",
                "db_table": "distribuidoras_datos",
            },
        ),
        migrations.CreateModel(
            name="CasaApuestas",
            fields=[
                ("id_casa", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("nro_perfiles", models.IntegerField(default=0)),
                ("url_backoffice", models.URLField()),
                (
                    "capital_activo_hoy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "capital_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("fecha_actualizacion_capital", models.DateTimeField(auto_now=True)),
                ("perfiles_minimos_req", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "distribuidora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casas",
                        to="gestion_operativa.distribuidora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Casa de Apuestas",
                "verbose_name_plural": "Casas de Apuestas",
                "db_table": "casas_apuestas",
            },
        ),
        migrations.CreateModel(
            name="PerfilOperativo",
            fields=[
                ("id_perfil", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=100)),
                (
                    "tipo_jugador",
                    models.CharField(
                        choices=[
                            ("PROFESIONAL", "Profesional"),
                            ("RECREATIVO", "Recreativo"),
                            ("CASUAL", "Casual"),
                            ("HIGH_ROLLER", "High Roller"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "deporte_dna",
                    models.CharField(
                        choices=[
                            ("FUTBOL", "Fútbol"),
                            ("BASKETBALL", "Basketball"),
                            ("TENNIS", "Tennis"),
                            ("BEISBOL", "Béisbol"),
                            ("AMERICANO", "Fútbol Americano"),
                            ("HOCKEY", "Hockey"),
                            ("BOXEO", "Boxeo"),
                            ("UFC", "UFC"),
                            ("OTROS", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_operativa", models.GenericIPAddressField(unpack_ipv4=True)),
                ("ciudad_sede", models.CharField(max_length=100)),
                ("preferencias", models.TextField(blank=True, null=True)),
                (
                    "nivel_cuenta",
                    models.CharField(
                        choices=[
                            ("BRONCE", "Bronce"),
                            ("PLATA", "Plata"),
                            ("ORO", "Oro"),
                            ("PLATINO", "Platino"),
                            ("DIAMANTE", "Diamante"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "saldo_real",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stake_promedio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("ops_semanales_actuales", models.IntegerField(default=0)),
                ("meta_ops_semanales", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfiles",
                        to="gestion_operativa.agencia",
                    ),
                ),
                (
                    "casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfiles",
                        to="gestion_operativa.casaapuestas",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfiles_operativos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Operativo",
                "verbose_name_plural": "Perfiles Operativos",
                "db_table": "perfiles_operativos",
            },
        ),
        migrations.CreateModel(
            name="BitacoraMando",
            fields=[
                ("id_bitacora", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("observacion", models.TextField()),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas_bitacora",
                        to="gestion_operativa.perfiloperativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora de Mando",
                "verbose_name_plural": "Bitácoras de Mando",
                "db_table": "bitacora_mando",
            },
        ),
        migrations.CreateModel(
            name="AlertaOperativa",
            fields=[
                ("id_alerta", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_alerta", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("severidad", models.CharField(max_length=20)),
                ("estado", models.CharField(max_length=50)),
                (
                    "casa_afectada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_operativa.casaapuestas",
                    ),
                ),
                (
                    "perfil_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_operativa.perfiloperativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta Operativa",
                "verbose_name_plural": "Alertas Operativas",
                "db_table": "alertas_operativas",
            },
        ),
        migrations.CreateModel(
            name="PlanificacionRotacion",
            fields=[
                (
                    "id_planificacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fecha", models.DateField()),
                (
                    "estado_dia",
                    models.CharField(
                        choices=[("A", "Activo"), ("D", "Descanso")], max_length=1
                    ),
                ),
                ("mes", models.IntegerField()),
                ("anio", models.IntegerField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planificaciones",
                        to="gestion_operativa.perfiloperativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planificación Rotación",
                "verbose_name_plural": "Planificaciones de Rotación",
                "db_table": "planificacion_rotacion",
            },
        ),
        migrations.CreateModel(
            name="TransaccionFinanciera",
            fields=[
                ("id_transaccion", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_transaccion", models.CharField(max_length=50)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_transaccion", models.DateTimeField()),
                ("metodo_pago", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=50)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="gestion_operativa.perfiloperativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción Financiera",
                "verbose_name_plural": "Transacciones Financieras",
                "db_table": "transacciones_financieras",
            },
        ),
    ]
