# Generated by Django 5.0.1 on 2026-01-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_operativa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casaapuestas",
            name="url_backoffice",
            field=models.URLField(blank=True, null=True),
        ),
    ]
