# Generated by Django 5.0.1 on 2026-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_operativa", "0002_alter_casaapuestas_url_backoffice"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfiloperativo",
            name="ops_historicas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="perfiloperativo",
            name="ops_mensuales",
            field=models.IntegerField(default=0),
        ),
    ]
