# Generated by Django 5.0.1 on 2026-01-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_operativa", "0003_perfiloperativo_ops_historicas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operacion",
            fields=[
                ("id_operacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora exacta de la operación",
                        null=True,
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stake o monto apostado",
                        max_digits=12,
                    ),
                ),
                (
                    "cuota",
                    models.DecimalField(
                        decimal_places=2, help_text="Odds de la apuesta", max_digits=6
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("GANADA", "Ganada"),
                            ("PERDIDA", "Perdida"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Retorno total (Stake + Profit)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Resultado neto (P&L)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("deporte", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "mercado",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Ganador del partido, Over 2.5",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operaciones_reales",
                        to="gestion_operativa.perfiloperativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operación",
                "verbose_name_plural": "Operaciones",
                "db_table": "operaciones",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
