# Generated by Django 5.0.1 on 2026-01-17 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_operativa", "0004_operacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                ("id_ubicacion", models.AutoField(primary_key=True, serialize=False)),
                ("pais", models.CharField(default="Perú", max_length=100)),
                (
                    "provincia_estado",
                    models.CharField(max_length=100, verbose_name="Provincia / Estado"),
                ),
                ("ciudad", models.CharField(max_length=100)),
                (
                    "direccion",
                    models.CharField(
                        max_length=255, verbose_name="Dirección exacta (Calles)"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Frente al parque...",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "link_google_maps",
                    models.URLField(
                        blank=True, help_text="Enlace exacto a Google Maps", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "db_table": "ubicaciones",
            },
        ),
        migrations.AddField(
            model_name="agencia",
            name="casa_madre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agencias",
                to="gestion_operativa.casaapuestas",
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="contacto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="agencia",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="agencia",
            name="perfiles_minimos",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="agencia",
            name="rake_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="% Rake", max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="url_backoffice",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="agencia",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="agencia",
            name="ubicacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agencias",
                to="gestion_operativa.ubicacion",
            ),
        ),
    ]
