# Generated by Django 5.0.1 on 2026-01-18 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_operativa",
            "0005_ubicacion_agencia_casa_madre_agencia_contacto_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfiloperativo",
            name="ciudad_sede",
        ),
        migrations.RemoveField(
            model_name="perfiloperativo",
            name="ops_historicas",
        ),
        migrations.RemoveField(
            model_name="perfiloperativo",
            name="ops_mensuales",
        ),
        migrations.RemoveField(
            model_name="perfiloperativo",
            name="ops_semanales_actuales",
        ),
        migrations.RemoveField(
            model_name="perfiloperativo",
            name="saldo_real",
        ),
        migrations.RemoveField(
            model_name="perfiloperativo",
            name="stake_promedio",
        ),
        migrations.AddField(
            model_name="perfiloperativo",
            name="url_acceso_backoffice",
            field=models.URLField(
                blank=True, help_text="Link al backoffice de la cuenta", null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfiloperativo",
            name="casa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfiles",
                to="gestion_operativa.casaapuestas",
            ),
        ),
    ]
