# Generated by Django 5.0.1 on 2026-01-18 06:39

import django.db.models.deletion
from django.db import migrations, models


def create_default_persona(apps, schema_editor):
    Persona = apps.get_model("gestion_operativa", "Persona")
    if not Persona.objects.filter(pk=1).exists():
        Persona.objects.create(
            id_persona=1,
            primer_nombre="Default",
            primer_apellido="Persona",
            tipo_documento="OTRO",
            numero_documento="DEFAULT-000",
            fecha_nacimiento="2000-01-01",
            pais="Ecuador",
            telefono="0000000000",
            correo_electronico="default@system.com",
            activo=False,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_operativa", "0006_remove_perfiloperativo_ciudad_sede_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("id_persona", models.AutoField(primary_key=True, serialize=False)),
                ("primer_nombre", models.CharField(max_length=100)),
                (
                    "segundo_nombre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("primer_apellido", models.CharField(max_length=100)),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CEDULA", "Cédula de Identidad"),
                            ("PASAPORTE", "Pasaporte"),
                            ("LICENCIA", "Licencia de Conducir"),
                            ("DNI", "DNI"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=50, unique=True)),
                ("fecha_nacimiento", models.DateField()),
                ("pais", models.CharField(default="Ecuador", max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("correo_electronico", models.EmailField(max_length=254, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "foto_rostro",
                    models.ImageField(
                        blank=True, null=True, upload_to="personas/fotos/"
                    ),
                ),
                (
                    "documento_frente",
                    models.ImageField(
                        blank=True, null=True, upload_to="personas/documentos/"
                    ),
                ),
                (
                    "documento_reverso",
                    models.ImageField(
                        blank=True, null=True, upload_to="personas/documentos/"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "db_table": "personas",
            },
        ),
        migrations.RunPython(create_default_persona),
        migrations.AddField(
            model_name="perfiloperativo",
            name="persona",
            field=models.ForeignKey(
                default=1,
                help_text="Datos de identidad usados para crear esta cuenta",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfiles",
                to="gestion_operativa.persona",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="perfiloperativo",
            unique_together={("persona", "casa")},
        ),
    ]
