# Generated by Django 5.0.1 on 2026-01-18 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_default_deportes(apps, schema_editor):
    """Crear los 11 deportes iniciales."""
    Deporte = apps.get_model("gestion_operativa", "Deporte")
    deportes = [
        "Fútbol",
        "Básketbol",
        "Tenis",
        "Béisbol",
        "Fútbol Americano",
        "Hockey",
        "MMA/UFC",
        "Boxeo",
        "eSports",
        "Cricket",
        "Tenis De Mesa",
    ]
    for nombre in deportes:
        Deporte.objects.get_or_create(nombre=nombre)


def clear_deporte_fields(apps, schema_editor):
    """Limpiar campos de texto deporte antes de convertir a FK."""
    PerfilOperativo = apps.get_model("gestion_operativa", "PerfilOperativo")
    Operacion = apps.get_model("gestion_operativa", "Operacion")
    # Set to NULL so FK conversion doesn't fail
    PerfilOperativo.objects.all().update(deporte_dna=None)
    Operacion.objects.all().update(deporte=None)


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_operativa", "0007_persona_perfiloperativo_persona_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deporte",
            fields=[
                ("id_deporte", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50, unique=True)),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono para UI",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Deporte",
                "verbose_name_plural": "Deportes",
                "db_table": "deportes",
                "ordering": ["nombre"],
            },
        ),
        migrations.RunPython(create_default_deportes),
        # First, make deporte_dna and deporte nullable as CharFields
        migrations.AlterField(
            model_name="perfiloperativo",
            name="deporte_dna",
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="operacion",
            name="deporte",
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        # Now clear the text values
        migrations.RunPython(clear_deporte_fields),
        migrations.AlterModelOptions(
            name="transaccionfinanciera",
            options={
                "ordering": ["-fecha_transaccion"],
                "verbose_name": "Transacción Financiera",
                "verbose_name_plural": "Transacciones Financieras",
            },
        ),
        migrations.AddField(
            model_name="transaccionfinanciera",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaccionfinanciera",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Número de comprobante o referencia bancaria",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaccionfinanciera",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="distribuidora",
            name="deportes",
        ),
        migrations.AlterField(
            model_name="operacion",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Fecha y hora exacta de la operación",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaccionfinanciera",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("COMPLETADA", "Completada"),
                    ("RECHAZADA", "Rechazada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaccionfinanciera",
            name="fecha_transaccion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transaccionfinanciera",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("USDT", "USDT (Tether)"),
                    ("SKRILL", "Skrill"),
                    ("NETELLER", "Neteller"),
                    ("BANCO", "Transferencia Bancaria"),
                    ("EFECTIVO", "Efectivo"),
                    ("PAYPAL", "PayPal"),
                    ("CRIPTO_OTRO", "Otra Criptomoneda"),
                ],
                help_text="Método de pago utilizado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaccionfinanciera",
            name="tipo_transaccion",
            field=models.CharField(
                choices=[
                    ("DEPOSITO", "Depósito"),
                    ("RETIRO", "Retiro"),
                    ("AJUSTE", "Ajuste"),
                    ("BONO", "Bono"),
                ],
                help_text="Tipo de movimiento financiero",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="operacion",
            name="deporte",
            field=models.ForeignKey(
                blank=True,
                help_text="Deporte de la apuesta",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operaciones",
                to="gestion_operativa.deporte",
            ),
        ),
        migrations.AlterField(
            model_name="perfiloperativo",
            name="deporte_dna",
            field=models.ForeignKey(
                blank=True,
                help_text="Deporte principal del perfil",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfiles_dna",
                to="gestion_operativa.deporte",
            ),
        ),
        migrations.AddField(
            model_name="distribuidora",
            name="deportes",
            field=models.ManyToManyField(
                blank=True,
                related_name="distribuidoras",
                to="gestion_operativa.deporte",
            ),
        ),
    ]
