# Generated by Django 5.0.1 on 2026-01-18 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_operativa",
            "0008_deporte_alter_transaccionfinanciera_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertaoperativa",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Alerta Operativa",
                "verbose_name_plural": "Alertas Operativas",
            },
        ),
        migrations.RemoveField(
            model_name="configuracionoperativa",
            name="actualizar_meta_diariamente",
        ),
        migrations.RemoveField(
            model_name="configuracionoperativa",
            name="meta_volumen_diario",
        ),
        migrations.RemoveField(
            model_name="configuracionoperativa",
            name="umbral_saldo_critico",
        ),
        migrations.AddField(
            model_name="alertaoperativa",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alertaoperativa",
            name="resuelta_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertaoperativa",
            name="resuelta_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_resueltas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="configuracionoperativa",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="configuracionoperativa",
            name="volumen_apostado_hoy",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="SUM de importe de operaciones de hoy",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="alertaoperativa",
            name="casa_afectada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas",
                to="gestion_operativa.casaapuestas",
            ),
        ),
        migrations.AlterField(
            model_name="alertaoperativa",
            name="descripcion",
            field=models.TextField(help_text="Descripción detallada de la alerta"),
        ),
        migrations.AlterField(
            model_name="alertaoperativa",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ACTIVA", "Activa"),
                    ("EN_REVISION", "En Revisión"),
                    ("RESUELTA", "Resuelta"),
                ],
                default="ACTIVA",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="alertaoperativa",
            name="perfil_afectado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas",
                to="gestion_operativa.perfiloperativo",
            ),
        ),
        migrations.AlterField(
            model_name="alertaoperativa",
            name="severidad",
            field=models.CharField(
                choices=[
                    ("BAJA", "Baja"),
                    ("MEDIA", "Media"),
                    ("ALTA", "Alta"),
                    ("CRITICA", "Crítica"),
                ],
                default="MEDIA",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alertaoperativa",
            name="tipo_alerta",
            field=models.CharField(
                choices=[
                    ("SALDO_CRITICO", "Saldo Crítico"),
                    ("ESCASEZ_OPERATIVA", "Escasez Operativa"),
                    ("CAPITAL_INSUFICIENTE", "Capital Insuficiente"),
                    ("META_NO_ALCANZADA", "Meta No Alcanzada"),
                    ("INACTIVIDAD", "Inactividad Prolongada"),
                ],
                help_text="Tipo de alerta detectada",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="configuracionoperativa",
            name="capital_total_activos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="SUM de saldos de perfiles activos hoy",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="configuracionoperativa",
            name="perfiles_en_descanso",
            field=models.IntegerField(
                default=0, help_text="COUNT de perfiles en descanso hoy"
            ),
        ),
        migrations.AlterField(
            model_name="configuracionoperativa",
            name="perfiles_listos_operar",
            field=models.IntegerField(
                default=0, help_text="COUNT de perfiles activos hoy"
            ),
        ),
        migrations.CreateModel(
            name="ProtocoloAuditoria",
            fields=[
                ("id_protocolo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "perfiles_minimos_por_casa",
                    models.IntegerField(
                        default=3, help_text="Mínimo de perfiles activos por casa"
                    ),
                ),
                (
                    "umbral_saldo_critico",
                    models.DecimalField(
                        decimal_places=2,
                        default=300,
                        help_text="Saldo mínimo por perfil antes de alerta",
                        max_digits=12,
                    ),
                ),
                (
                    "capital_seguridad_por_casa",
                    models.DecimalField(
                        decimal_places=2,
                        default=2000,
                        help_text="Capital mínimo total por casa",
                        max_digits=12,
                    ),
                ),
                (
                    "volumen_diario_objetivo",
                    models.DecimalField(
                        decimal_places=2,
                        default=6000,
                        help_text="Meta de volumen de apuestas diario",
                        max_digits=12,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocolos_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocolo de Auditoría",
                "verbose_name_plural": "Protocolos de Auditoría",
                "db_table": "protocolo_auditoria",
            },
        ),
    ]
