# Generated by Django 5.0.1 on 2026-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="numero_contacto",
        ),
        migrations.AddField(
            model_name="user",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[("ADMIN", "Administrador"), ("OPERADOR", "Operador")],
                default="OPERADOR",
                max_length=20,
            ),
        ),
    ]
